name: Build nightly

on:
  push:
    branches: ["master"]
    paths-ignore:
      - 'README.md'
      - archived
      - default
      - staging
      - template
      - tools
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    name: Build with Docker using devkitARM
    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        run: git config --global safe.directory '*'
      - name: Build all drivers
        run: |
          chmod +x build.sh
          ./build.sh
      - uses: actions/upload-artifact@v4
        with:
          path: out
          name: build
      - name: Checkout artifact branch
        uses: actions/checkout@v4
        with:
          path: artifacts
          ref: builds
      - name: Commit artifacts
        continue-on-error: true
        run: |
          rm -rf artifacts/*.dldi
          cp -r out/*.dldi artifacts/
          cd artifacts
          git add .
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Build: ${{ github.sha }}"
      - name: Push changes
        uses: ad-m/github-push-action@master
        continue-on-error: true
        with:
          directory: artifacts
          branch: builds
